# docker-compose.yml

version: "3.7"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ctf-platform
    ports:
      - '5432:5432'
    volumes:
      - ctf-db:/var/lib/postgresql/data

  server:
    build:
      context: ./Interactive-challenge-node
    environment:
      DB_SCHEMA: ctf-platform
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '80:8080'

volumes:
    ctf-db:
